# Generated by Django 4.1.2 on 2023-01-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_contactp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactp',
            old_name='data',
            new_name='Mno',
        ),
        migrations.RenameField(
            model_name='contactp',
            old_name='plan',
            new_name='bname',
        ),
        migrations.RemoveField(
            model_name='contactp',
            name='service',
        ),
        migrations.RemoveField(
            model_name='contactp',
            name='validity',
        ),
    ]
