# Generated by Django 4.1.2 on 2023-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_data_contactp_mno_rename_plan_contactp_bname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactp',
            name='Mno',
            field=models.CharField(max_length=10),
        ),
    ]
