# Generated by Django 4.1.2 on 2023-01-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_contactp_mno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=100)),
                ('Mno', models.CharField(max_length=10)),
                ('OPERATOR', models.CharField(max_length=100)),
                ('PLAN', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactP',
        ),
    ]
